### ISSUE TITLE
Vytvořit hezčí výpis pro LIST_DIR (výpis souborů)

### ISSUE THREAD

**Issue by Bloc3k** [martin-nohava/kryzbu#10]
Zatím je LIST_DIR implementovaný tak, že se na serveru vytvoří `list` s názvy souborů a ten se odešle po sítí. U klienta je pak vyobrazen jako čistý `python list`. 

Bylo by vhodné soubory vypisovat v hezčím formátu. Případně ze serveru posílat i velikosti jednotlivých souborů a přidat tuto informaci k výpisu.

**Comment by martin-nohava** [comment]
První úprava v commitu f87e469a8100c872d32e9143a35bd29f8b9622dd.
Výpis již využívá údaje z databáze, ne ze systému. Přidán výpis data nahrání, počet stažení, vlastníka apod.

**Comment by martin-nohava** [comment]
Druhá úprava, vylepšení formátovaného výpisu do konzole.
Ref. 29c56b13d34aa28122185579c8bfa8ac263b0582

**Comment by martin-nohava** [comment]
<img width="599" alt="Snímek obrazovky 2022-03-03 v 16 45 53" src="https://user-images.githubusercontent.com/57003339/156600321-8f876446-f4c7-4c80-b924-aac61537ec10.png">
