### ISSUE TITLE
Vytvořit databázi pro indexaci souborů na serveru

### ISSUE THREAD

**Issue by martin-nohava** [martin-nohava/kryzbu#11]
Vytvořením databáze o uložených soubore, bude možné zajistit ošetření problému v issue #9 i případně lépe formátované výpisy obsahující více dat (datum, velikost souboru, vlastník apod.), issue #10.

**Comment by Bloc3k** [comment]
Databáze pro indexování souborů vytvořena v commitu e13cfe7a3993eeac8fa708b8c08f98c2b5264300.  

Tímto uzavírám tuto issue.
