### ISSUE TITLE
Stahování souborů do výchozí složky pro stahování dle OS

### ISSUE THREAD

**Issue by martin-nohava** [martin-nohava/kryzbu#12]
Kód je připraven, pouze je v kolizi s kódem přidaným v commitu d6419b27f4c85cd085b1677cea789aa1759eea1f.

Navržená úprava
```python
# Receive file
with open(str(os.path.join(os.path.expanduser('~/Downloads'), file_name)), "wb") as f:
    while True:
        bytes_read = client.recv(Client.BUFFER_SIZE)
        if not bytes_read:
            break
        f.write(bytes_read)
        progress.update(len(bytes_read))
```

Mám to přepsat, nebo použijeme to tvoje? @Bloc3k

**Comment by Bloc3k** [comment]
> Kód je připraven, pouze je v kolizi s kódem přidaným v commitu [d6419b2](https://github.com/martin-nohava/kryzbu/commit/d6419b27f4c85cd085b1677cea789aa1759eea1f).
> 
> Navržená úprava
> 
> ```python
> # Receive file
> with open(str(os.path.join(os.path.expanduser('~/Downloads'), file_name)), "wb") as f:
>     while True:
>         bytes_read = client.recv(Client.BUFFER_SIZE)
>         if not bytes_read:
>             break
>         f.write(bytes_read)
>         progress.update(len(bytes_read))
> ```
> 
> Mám to přepsat, nebo použijeme to tvoje? @Bloc3k

Vypadá to dobře, udělej to tak.
Jen jsem si říkal, že tu složku s daty serveru jsme naschvál dali k projektu aby to bylo u sebe a teď tohle dáme pryč.

**Comment by martin-nohava** [comment]
Věci nahrané na server, by rozhodně s ním měly být pevně spojené, ale u stažených ke klientovi si naopak myslím bude uživatelsky přívětivější je ukládat do stažených souborů.

**Comment by martin-nohava** [comment]
Implementováno commitem dee8f8ad08df0b9b7cf0a7a8e94f523024536cd9.
