### ISSUE TITLE
Přidání '--set-download-folder' pro klienta

### ISSUE THREAD

**Issue by Bloc3k** [martin-nohava/kryzbu#14]
Klientem stažené soubory jsou automaticky staženy do C:/downloads na windejvsu. Já mám C: pouze pro systém. Bylo by fajn mít možnost rozhodnout se kam to chci stáhnout. Například přidat `--set-download-folder` přepínač pro klientskou CLI, pro nastavení jiného adresáře pro download.

**Comment by martin-nohava** [comment]
V tom případě bude ale muste mít klient nějaký soubor, např. `settings.conf` kde se bude ukládat jeho nastavení.
Případně by se to muselo zadávat s každým požadavkem na stažení, ale nevím jestli se ti to bude chtít pořád vypisovat celý. 😅

**Comment by Bloc3k** [comment]
Pravda, zatím to necháme ležet.
