### ISSUE TITLE
Detailní a zkrácený výpis dostupných souborů

### ISSUE THREAD

**Issue by Bloc3k** [martin-nohava/kryzbu#15]
Nyní existuje pouze detailní popis dostupných souborů na serveru (LIST_DIR). Chování podobné `ls -al` v linuxu. 

![image](https://user-images.githubusercontent.com/43991228/156598161-e551565b-3688-4b28-979a-b63f421daff6.png)

Navrhuji přidat i zkrácenou verzi výpisu, kde by se vypsala pouze jména souborů, tak jak je tomu při  samotném `ls` bez přepínače. 

![image](https://user-images.githubusercontent.com/43991228/156598089-c95248fb-39e1-4a15-ac5c-d82446179393.png)

Možná implementace: V souboru `client.py` ve funkci `list_files()` přidat parametr, který by pomocí  `if`  přepínal mezi detailním a zkráceným výpisem.

> Když přijde od serveru FileNotFoud při DOWNLOADu, klientovi se do konsole vypíší dostupné soubory. Zde by bylo použití zkráceného (pouze informativního) výpisu skvělé.

**Comment by martin-nohava** [comment]
Implementováno v 239da6925cf64ef5261faafff0c82898acb3338d.
<img width="597" alt="Snímek obrazovky 2022-03-03 v 21 30 05" src="https://user-images.githubusercontent.com/57003339/156647883-b703f509-8e4a-4296-9dc1-e5a53754598c.png">
