### ISSUE TITLE
Vytvořit parser argumentů pro `kryzbu_server.py`

### ISSUE THREAD

**Issue by martin-nohava** [martin-nohava/kryzbu#2]
Návrh potřebných argumentů pro `kryzbu_server.py` a implementace jejich parsování.

**Comment by Bloc3k** [comment]
Parser možná nebude ani potřeba. Server se bude spouštet bez přepínače a najede do základní smyčky naslouchání a až podle komunikace s klientem bude spouště konkrétní obslužné metody.
