### ISSUE TITLE
Stahováni z databáze

### ISSUE THREAD

**Issue by Kaspis123** [martin-nohava/kryzbu#26]
Při stahování z databáze není vidět načítání baru, je celou dobu prázdný a když je soubor stažen tak se teprve naplní na 100%.

**Comment by Bloc3k** [comment]
Toto zítra vyřeším. Problém je v tom že reader čte celý soubor ze streamu najednou a await ho drží. Takže se nemůže vykreslovat progessbar. Udělám wby se načítaly konstantní useky dat mezi kterými s ebude progresbar aktualizovat.

**Comment by Bloc3k** [comment]
6cb253b07f5fa888c51eb442f267336a722ac5f7 resolves
