### ISSUE TITLE
Vypisování souboru

### ISSUE THREAD

**Issue by Kaspis123** [martin-nohava/kryzbu#27]
Chtělo by prohodit vypisování souborů, tak aby nevadil dlouhý název. 
![image](https://user-images.githubusercontent.com/62380209/156927700-5d3ac968-6cde-4b3b-a718-e65a5c87a399.png)

**Comment by Bloc3k** [comment]
@martin-nohava mohl by jsi to prohodit až budeš něco commitovat?.
