### ISSUE TITLE
Vytvořit parser argumentů pro `kryzbu.py`

### ISSUE THREAD

**Issue by martin-nohava** [martin-nohava/kryzbu#3]
Návrh potřebných argumentů pro `kryzbu.py` a implementace jejich parsování.

**Comment by Bloc3k** [comment]
Issue je moc rozsáhlá, nedá se jednoznačně splnit + část už je implementována. Z tohoto duvodu issue uzavírám a budou případně otevřený nové issue pro implementaci konkrétních přepínačů.
