### ISSUE TITLE
Při uspěšném switchy uživatele server vyhodí error (nemá vliv na běh serveru

### ISSUE THREAD

**Issue by Bloc3k** [martin-nohava/kryzbu#36]

**Comment by Bloc3k** [comment]
Po uspěšné změně uživatele server vyhazuej error. Error nemá vliv na chod serveru ani klienta, dálší dotazy projdou v pořádku

server
![image](https://user-images.githubusercontent.com/43991228/161131397-50990e99-cc09-494c-beda-a573d74ff5c3.png)

client
![image](https://user-images.githubusercontent.com/43991228/161131430-b6d26343-cdfd-494c-be40-422576146b36.png)

**Comment by martin-nohava** [comment]
Oprava implementována v f8b75e92781070c0b6081387d8eed1aa2f96c952.
