### ISSUE TITLE
Dotaz od neregistrovaného uživatele vyhodí chybu na serveru

### ISSUE THREAD

**Issue by Bloc3k** [martin-nohava/kryzbu#37]
server:

![image](https://user-images.githubusercontent.com/43991228/161373622-7e10749f-90e0-4dfc-bfb9-e879d955f3d7.png)

client:

![image](https://user-images.githubusercontent.com/43991228/161373658-b591b1c6-ecef-43ae-a649-ce89bf267b9b.png)

Vyhazuje stejnou chybu i pro `download` , `upload` i `list_dir`

**Comment by martin-nohava** [comment]
Jak jsi vytvořil neregistrovaného uživatele?

**Comment by Bloc3k** [comment]
asi zůstal z předchozího
