### ISSUE TITLE
Informace o klientovi nevypisují pod jakým účtem je uživatel přihlášen

### ISSUE THREAD

**Issue by Bloc3k** [martin-nohava/kryzbu#38]
Když dám `kryzbu.py -i` tak mi to dřív vypsalo pod kým jsem přihlášen, default download adresář apod.

Ted to vypíše toto:

![image](https://user-images.githubusercontent.com/43991228/161375190-04e9d886-ea0e-4ab0-a721-ab822d171c74.png)

**Comment by martin-nohava** [comment]
Aha, my bad, kolize v pojmenování metod se dívám.
