### ISSUE TITLE
Zdokumentovat jednotlivé funkce kódu

### ISSUE THREAD

**Issue by Bloc3k** [martin-nohava/kryzbu#40]
Automatické generování dokumentace z docstrings v kódu je již imlementováno. **Nyní je potřeba vytvořit docstrings pro jednotlivé funcke v kódu, které chceme mít zdokumentovány.** 

# Client/client.py

- [x] Popis hlavní třídy
- [x] open_connection
- [x] load_aes_key
- [x] send_request
- [x] upload
- [x] download
- [x] remove
- [x] list_files
- [x] init
- [x] online_operation
- [x] get_server_publickey
- [x] user_exists
- [x] login
- [x] get_download_folder
- [x] set_download_folder
- [x] info
- [x] get_username
- [x] change_user
- [x] flush_key
- [x] version

# Server/loglib.py

- [x] Popis hlavní třídy
- [x] event
- [x] write
- [x] verify

# Server/rsalib.py

- [x] Popis hlavní třídy
- [x] init
- [x] get_pub_key_location
- [x] get_priv_key_location

# Server/server.py

- [x] Popis hlavní třídy
- [x] start
- [x] run
- [x] handle_connection
- [x] init
- [x] recieve_file
- [x] serve_file
- [x] remove_file
- [x] list_files
- [x] send_pubkey
- [x] autenticate
- [x] version

# Server/db.py

## Hmac_index

- [x] Popis hlavní třídy Hmac_index
- [x] init
- [x] add
- [x] update
- [x] get_record
- [x] table_exists
- [x] file_exists

## User_db

- [x] Popis hlavní třídy User_db
- [x] init
- [x] add
- [x] delete
- [x] get_record
- [x] return_all
- [x] show_all
- [x] table_exists
- [x] name_exists

## File_index

- [x] Popis hlavní třídy File_index
- [x] init
- [x] add
- [x] download
- [x] delete
- [x] refresh
- [x] show_all
- [x] user_owns
- [x] user_files
- [x] return_all
- [x] get_record
- [x] table_exists
- [x] file_exists

**Comment by martin-nohava** [comment]
Prosím o kontrolu @Bloc3k, můžeme uzavřít?

**Comment by Bloc3k** [comment]
Jop, vypadá to pěkně. Všechny funkce jsou zdokumentované a tak uzavíráme tuto issue.
