### ISSUE TITLE
Napsat studii

### ISSUE THREAD

**Issue by martin-nohava** [martin-nohava/kryzbu#5]
**Kontrolní studie**:
Do 6. týdne semestru je povinnost odevzdat studii problematiky, která bude obsahovat (titulní strana, obsah, úvod, závěr, přílohy, literatura dle ISO 690):
• úvod a popis projektu,
• cíle projektu, kterých by mělo být dosaženo,
• teoretickou část popisující vybrané téma,
• aktuální stav řešení (popis v jaké fázi řešení se projekt nachází (čeho bylo dosaženo) a jak bude dále probíhat (**návrh dalšího postupu**),
• představit autory a uvést jejich pracovní přínos do projektu.
Rozsah je stanoven na 4 – 7 stran (dle složitosti problematiky). Inspirovat se můžete některým z odborných článků dostupných na internetu. Doporučená je konzultace s vyučujícím, aby se váš projekt nebral špatným směrem.

**Comment by Kaspis123** [comment]
In progress by Ikachuu

**Comment by Bloc3k** [comment]
Dobré by bylo do studie pak nějak využít toho, že budeme mít plně funkční nešifrovanou i šifrovanou verzi. Udělat nějaké porovnání třeba ve wiresharku nebo nějaké porovnání výstupu koďu šifrovaného a nešifrovaného.

**Comment by Bloc3k** [comment]
obhájeno
