### ISSUE TITLE
Vytvoření systému logování

### ISSUE THREAD

**Issue by martin-nohava** [martin-nohava/kryzbu#6]
Základní implementace vytváření jednoduchých logů o událostech v systému.

**Comment by Bloc3k** [comment]
S tímto nemusíme.asi moc spěchat. Kód a možná i celková funkcionalita se bude v budoucnu měnit.

**Comment by martin-nohava** [comment]
V commitu c9038e5e4c5b87c474400e4aeeb8d62b76ad9e22 byla přidána základní funkcionalita logování pomocí souboru `loglib.py`. V současné podobě dokáže zaznamenávat události `UPLOAD` a `DOWNLOAD`.

**Comment by martin-nohava** [comment]
Základní funkcionalita je dostatečná, uzavírám.
