### ISSUE TITLE
Zajistit kompatibilitu s Unix-like systémy

### ISSUE THREAD

**Issue by martin-nohava** [martin-nohava/kryzbu#7]
V současné podobě kód podporuje pouze platformu Windows.

**Comment by martin-nohava** [comment]
Podpora pro upload přidána v 8f3cf6ffb35fa89fb6976a89842339700f10bbb8

**Comment by martin-nohava** [comment]
Byla navržena i nová struktura složek na straně serveru pro ukládání souborů a servisních dat. (Viz obrázek.) Po uploadu se soubor uloží do adresáře `server/_data/files/<jmeno_souboru.koncovka>`.

Navrhuji úpravu obsahu proměnné `file_name` v `client.py`. V současné době neobsahuje pouze název souboru, ale (obsahuje/může obsahovat) i cestu k němu. Je to zmatečné a na straně serveru zbytečná informace. Lze ořezat pomocí `os.path.basename(filename)`.
Názory? @Bloc3k 

![Snímek obrazovky 2022-02-28 v 21 24 56](https://user-images.githubusercontent.com/57003339/156053503-1183d464-5a9e-4431-a7ee-026dd0391965.png)

**Comment by Bloc3k** [comment]
změna nazvu proměné file_name je dobrý navrh a změnu provedeme. Teď se to ořezává na serveru. Jak jsi říkal serveru stačí vědět jméno pod kterým má soubor uložit. Navrhuji aby se ořezávání provádělo již na straně klienta (podobně jak to udělal kašpy v jeho commitu).

**Comment by Bloc3k** [comment]
Pullnul jsem si commit [8f3cf6](https://github.com/martin-nohava/kryzbu/commit/8f3cf6ffb35fa89fb6976a89842339700f10bbb8) spustil a vyhodilo tento error.

![image](https://user-images.githubusercontent.com/43991228/156178329-b0600aac-5a98-4bf3-93be-2f36f40acfc5.png)

Zjistil jsem že jako referenční adresář mi to používá kořenový adresář projektu `\kryzbu\` tudiž nevidí přímo adresář `\server\`. 

Úprava 16 řádku v `server.py`:
```
SERVER_FOLDER = Path("src/server/_data/files/")
```
pomohla a pak to funguje. Ale tipuji že pak se to rozbije tobě. 
Co s tím nevím. proto píšu

**Comment by martin-nohava** [comment]
> Úprava 16 řádku v `server.py`:
> 
> ```
> SERVER_FOLDER = Path("src/server/_data/files/")
> ```
> 
> pomohla a pak to funguje. Ale tipuji že pak se to rozbije tobě. Co s tím nevím. proto píšu

Možná bude záležet z jakého adresáře to pouštíš. Zapínáš to jako `python3 server.py` a nebo `python3 src/server.py` a nebo něco takového.

**Comment by Bloc3k** [comment]
Ano spouštěl jsem to z VSC a ten to bral z root adresáře. už to funguje

Jinak [návrh na změnu](https://github.com/martin-nohava/kryzbu/issues/7#issuecomment-1054638273) názvu proměnné byl přijat a proměnná změněna v 460ff0122b040ea46af994165f4cf9566218e18c, proto tuto issue timto uzavírám.
