### ISSUE TITLE
Název souboru nemůže obsahovat mezery

### ISSUE THREAD

**Issue by martin-nohava** [martin-nohava/kryzbu#8]

**Comment by martin-nohava** [comment]
Při pokusu o upload souboru s mezerou v názvu dojde k pádu serveru.

**Klient:**
```python3 kryzbu.py -u /Users/martin_nohava/Desktop/testfile\ 2.txt```

**Server:**
```Traceback (most recent call last):
  File "/Users/martin_nohava/Documents/kryzbu/src/kryzbu_server.py", line 11, in <module>
    server.Server.run()
  File "/Users/martin_nohava/Documents/kryzbu/src/server/server.py", line 33, in run
    _, file_name = request.split()
ValueError: too many values to unpack (expected 2)```

**Comment by Bloc3k** [comment]
To je proto že požadavek na upload má formát

`UPLOAD FILENAME`

Jednotlivé položky jsou odděleny mezerou. Když pak přijde FILENAME s mezerou tak si myslí že požadavek obsahuje další položku.   
Požadavek má pak tvar:

`UPLOAD prvničast druhačast`

**Comment by martin-nohava** [comment]
Chápu, navrhoval bych použít teda jiný oddělovač místo mezery

**Comment by Bloc3k** [comment]
Ještě by možná šlo mezery v názvu přeměnit na pomlčky. Ale použití jiného oddělovače mi přijde elegantnější.

Nějaké návrhy co použít jako **oddělovač**?

**Comment by martin-nohava** [comment]
Klasický středník by nefungoval?

**Comment by Bloc3k** [comment]
Oddělovače jsem předělal na středníky `;` v 046e099b7dc8f77f58ebcd5010f3ea63a9a1406f. Server nyní přijímá i soubory s mezerou v názvu.

Tímto uzavírám tuto issue.
